[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "eth-streams-py"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "eth_protocols_py",
    "eth_typeshed_py",
    "eth_rpc_py",
    "tortoise-orm",
]

# Enables the usage of setuptools_scm
[tool.setuptools_scm]
root = "../../"

[project.optional-dependencies]
lint = [
    "mypy",
    "ruff",
]
test = [
    "pytest==7.4.1",
    "pytest-cov==4.1.0",
    "coverage[toml]==7.3.1",
]
build = [
    "build[virtualenv]==1.0.3",
]
dev = [
    "tox",
    "eth-streams-py[lint]",
    "eth-streams-py[test]",
    "eth-streams-py[build]",
]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
