[build-system]
requires = ["setuptools>=68", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "sapphire-py"
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
    "cbor2",
    "eth_rpc-py",
    "eth_typing",
    "pynacl",
]

# Enables the usage of setuptools_scm
[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[project.optional-dependencies]
test = [
    "pytest==8.3.2",
    "pytest-asyncio==0.24.0",
    "pytest-cov==5.0.0",
    "coverage[toml]==7.3.1",
]
build = [
    "build[virtualenv]==1.0.3",
]
dev = [
    "tox",
    "sapphire-py[lint]",
    "sapphire-py[test]",
    "sapphire-py[build]",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_default_fixture_loop_scope = "session"
