name: Test and Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: |
          tox -e lint,py${{ matrix.python }}-build_eth_rpc,py${{ matrix.python }}-build_eth_typeshed,py${{ matrix.python }}-build_eth_protocols,py${{ matrix.python }}-build_eth_streams
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
  
