name: Publish Package

on:
  workflow_run:
    workflows: ["Test and Build"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build deps
        run: |
          pip install tox tox-gh-actions wheel build twine

      - name: Publish All Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --repository pypi packages/eth_rpc/dist/* \
                        packages/eth_typeshed/dist/* \
                        packages/eth_protocols/dist/* \
                        packages/eth_streams/dist/*